# docker-compose.yaml
version: "3.7"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php73
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        ports:
            - 8000:80
    db:
        container_name: mysql57
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            # MYSQL_HOST: localhost
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nvidly
            # MYSQL_USER: devuser
            # MYSQL_PASSWORD: devpass
        volumes:
            - ./database:/helper_files
        ports:
            - 6033:3306
