CREATE DATABASE nvidly;

USE nvidly;

# Create tables
CREATE TABLE IF NOT EXISTS stock
(
    stockID INT NOT NULL UNIQUE AUTO_INCREMENT,
    manufacturer VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL,
    specification VARCHAR(100) NOT NULL,
    stockCount INT NOT NULL,
    salePrice DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY(stockID)
);

ALTER TABLE stock AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS sale
(
    transactionID INT NOT NULL UNIQUE AUTO_INCREMENT,
    stockID INT NOT NULL,
    custID INT NOT NULL,
    quantity INT NOT NULL,
    totalPrice DOUBLE NOT NULL,
    saleDate DATE NOT NULL,
    PRIMARY KEY(transactionID)
);

ALTER TABLE sale AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS customer
(
    custID INT NOT NULL UNIQUE AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL,
    forename VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    PRIMARY KEY(custID)
);

ALTER TABLE customer AUTO_INCREMENT = 1;

# Create FKs
ALTER TABLE sale
ADD FOREIGN KEY (stockID)
REFERENCES stock(stockID)
;
    
ALTER TABLE sale
ADD FOREIGN KEY (custID)
REFERENCES customer(custID)
;