CREATE DATABASE nvidly;

USE nvidly;

# Create tables
CREATE TABLE IF NOT EXISTS Stock
(
    stockID INT NOT NULL UNIQUE AUTO_INCREMENT,
    manufacturer VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL,
    specification VARCHAR(100) NOT NULL,
    stockCount INT NOT NULL,
    salePrice DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY(stockID)
);

ALTER TABLE Stock AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS Sale
(
    transactionID INT NOT NULL UNIQUE AUTO_INCREMENT,
    stockID INT NOT NULL,
    custID INT NOT NULL,
    quantity INT NOT NULL,
    totalPrice DOUBLE NOT NULL,
    saleDate DATE NOT NULL,
    PRIMARY KEY(transactionID)
);

ALTER TABLE Sale AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS Customer
(
    custID INT NOT NULL UNIQUE AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL,
    forename VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    PRIMARY KEY(custID)
);

ALTER TABLE Customer AUTO_INCREMENT = 1;

# Create FKs
ALTER TABLE Sale
ADD FOREIGN KEY (stockID)
REFERENCES Stock(stockID)
;
    
ALTER TABLE Sale
ADD FOREIGN KEY (custID)
REFERENCES Customer(custID)
;